homeassistant:

  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 260
  unit_system: metric
  time_zone: Europe/Prague
  customize: !include customize.yaml
#  auth_providers:
#    - type: trusted_networks
#      trusted_networks:
#        - !secret trusted_network1
#        - !secret trusted_network2
# uncomment for iOS device add
#    - type: legacy_api_password
#      api_password: !secret API_pass

lovelace:

  mode: yaml

frontend:

  themes: !include themes.yaml
  javascript_version: auto
  
system_health:

#uncomment for iOS device add
#discovery:

config:

hassio:

cloud:

http:

#uncomment for iOS device add
#  api_password: !secret API_pass

#uncomment to re-enable public ssl access
#  ssl_certificate: !secret cer_dir
#  ssl_key: !secret key_dir
#  base_url: !secret my_host+port

updater:

# include_used_components: true
# discovery:
# discovery:

group: !include groups.yaml

automation: !include_dir_merge_list automations/

script: !include scripts.yaml

sensor: !include sensors.yaml

binary_sensor: !include binary_sensors.yaml

zone: !include zones.yaml

conversation:

history:
  exclude:
    domains:
    - calendar
    - history_graph
    - media_player
    - switch
    - input_boolean
    - automation
    entities:
    - sensor.dark_sky_cloud_coverage_0
    - sensor.dark_sky_daily_summary
    - sensor.dark_sky_daytime_high_apparent_temperature_0
    - sensor.dark_sky_daytime_high_temperature_0
    - sensor.dark_sky_dew_point_0
    - sensor.dark_sky_hourly_summary
    - sensor.dark_sky_humidity_0
    - sensor.dark_sky_icon
    - sensor.dark_sky_icon_0
    - sensor.dark_sky_minutely_summary
    - sensor.dark_sky_overnight_low_apparent_temperature_0
    - sensor.dark_sky_overnight_low_temperature_0
    - sensor.dark_sky_ozone_0
    - sensor.dark_sky_precip
    - sensor.dark_sky_precip_0
    - sensor.dark_sky_precip_intensity_0
    - sensor.dark_sky_precip_probability_0
    - sensor.dark_sky_pressure_0
    - sensor.dark_sky_summary
    - sensor.dark_sky_summary_0
    - sensor.dark_sky_temperature_0
    - sensor.dark_sky_visibility_0
    - sensor.dark_sky_wind_bearing_0
    - sensor.dark_sky_wind_gust_0
    - sensor.dark_sky_wind_speed_0
    - sensor.neo_coolcam_door_window_detector_access_control
    - sensor.neo_coolcam_door_window_detector_access_control_2
    - sensor.neo_coolcam_door_window_detector_alarm_level
    - sensor.neo_coolcam_door_window_detector_alarm_level_2
    - sensor.neo_coolcam_door_window_detector_alarm_type
    - sensor.neo_coolcam_door_window_detector_alarm_type_2
    - sensor.neo_coolcam_door_window_detector_sourcenodeid
    - sensor.neo_coolcam_door_window_detector_sourcenodeid_2
    - sensor.neo_coolcam_unknown_type_0200_id_1027_alarm_level
    - sensor.neo_coolcam_unknown_type_0200_id_1027_alarm_type
    - sensor.neo_coolcam_unknown_type_0200_id_1027_exporting
    - sensor.neo_coolcam_unknown_type_0200_id_1027_interval
    - sensor.neo_coolcam_unknown_type_0200_id_1027_interval_2
    - sensor.neo_coolcam_unknown_type_0200_id_1027_interval_3
    - sensor.neo_coolcam_unknown_type_0200_id_1027_interval_4
    - sensor.neo_coolcam_unknown_type_0200_id_1027_power_management
    - sensor.neo_coolcam_unknown_type_0200_id_1027_previous_reading
    - sensor.neo_coolcam_unknown_type_0200_id_1027_previous_reading_2
    - sensor.neo_coolcam_unknown_type_0200_id_1027_previous_reading_3
    - sensor.neo_coolcam_unknown_type_0200_id_1027_previous_reading_4
    - sensor.neo_coolcam_unknown_type_0200_id_1027_sourcenodeid
    - sensor.popp_unknown_type_0004_id_0014_sourcenodeid


recorder:
  db_url: !secret maria_url
  purge_keep_days: 3
  exclude:
    domains:
    - calendar
    - history_graph
    - media_player
    - switch
    - input_boolean
    entities:
    - sensor.dark_sky_cloud_coverage_0
    - sensor.dark_sky_daily_summary
    - sensor.dark_sky_daytime_high_apparent_temperature_0
    - sensor.dark_sky_daytime_high_temperature_0
    - sensor.dark_sky_dew_point_0
    - sensor.dark_sky_hourly_summary
    - sensor.dark_sky_humidity_0
    - sensor.dark_sky_icon
    - sensor.dark_sky_icon_0
    - sensor.dark_sky_minutely_summary
    - sensor.dark_sky_overnight_low_apparent_temperature_0
    - sensor.dark_sky_overnight_low_temperature_0
    - sensor.dark_sky_ozone_0
    - sensor.dark_sky_precip
    - sensor.dark_sky_precip_0
    - sensor.dark_sky_precip_intensity_0
    - sensor.dark_sky_precip_probability_0
    - sensor.dark_sky_pressure_0
    - sensor.dark_sky_summary
    - sensor.dark_sky_summary_0
    - sensor.dark_sky_temperature_0
    - sensor.dark_sky_visibility_0
    - sensor.dark_sky_wind_bearing_0
    - sensor.dark_sky_wind_gust_0
    - sensor.dark_sky_wind_speed_0
    - sensor.neo_coolcam_door_window_detector_access_control
    - sensor.neo_coolcam_door_window_detector_access_control_2
    - sensor.neo_coolcam_door_window_detector_alarm_level
    - sensor.neo_coolcam_door_window_detector_alarm_level_2
    - sensor.neo_coolcam_door_window_detector_alarm_type
    - sensor.neo_coolcam_door_window_detector_alarm_type_2
    - sensor.neo_coolcam_door_window_detector_sourcenodeid
    - sensor.neo_coolcam_door_window_detector_sourcenodeid_2
    - sensor.neo_coolcam_unknown_type_0200_id_1027_alarm_level
    - sensor.neo_coolcam_unknown_type_0200_id_1027_alarm_type
    - sensor.neo_coolcam_unknown_type_0200_id_1027_exporting
    - sensor.neo_coolcam_unknown_type_0200_id_1027_interval
    - sensor.neo_coolcam_unknown_type_0200_id_1027_interval_2
    - sensor.neo_coolcam_unknown_type_0200_id_1027_interval_3
    - sensor.neo_coolcam_unknown_type_0200_id_1027_interval_4
    - sensor.neo_coolcam_unknown_type_0200_id_1027_power_management
    - sensor.neo_coolcam_unknown_type_0200_id_1027_previous_reading
    - sensor.neo_coolcam_unknown_type_0200_id_1027_previous_reading_2
    - sensor.neo_coolcam_unknown_type_0200_id_1027_previous_reading_3
    - sensor.neo_coolcam_unknown_type_0200_id_1027_previous_reading_4
    - sensor.neo_coolcam_unknown_type_0200_id_1027_sourcenodeid
    - sensor.popp_unknown_type_0004_id_0014_sourcenodeid
    
logbook:

map:

sun:

tts:

  - platform: google

logger:

  default: debug
  logs:
    homeassistant.components.mqtt: warn
    homeassistant.components.websocket_api: warn
    homeassistant.components.deluge_client: warn
#    homeassistant.components.nest: debug
#    homeassistant.components.sensor.nest: debug
#    sseclient: debug
#    homeassistant.components.camera: debug
#    homeassistant.components.sensor.imap_email_content: debug
#    homeassistant.components.imap_email_content: debug
#    homeassistant.components.sensor: debug
#cloud:

custom_updater:
  track:
    - cards
    - components
    - python_scripts
  component_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
  python_script_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/python_scripts.json
  card_urls:
    - https://raw.githubusercontent.com/rdehuyss/homeassistant-lovelace-google-calendar-card/master/custom_updater.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json
    - https://raw.githubusercontent.com/nervetattoo/simple-thermostat/master/tracker.json
    - https://raw.githubusercontent.com/sgttrs/lovelace-weather-card-chart/master/custom-updater.json

switch:

  - platform: command_line
    switches:
      shuffle:
        friendly_name:  Shuffle
        command_on: !secret shuffle_on_cmd
        command_off: !secret shuffle_off_cmd

evohome:

  username: !secret my_email
  password: !secret hass_pass
  location_idx: 0
  scan_interval: 360 

media_player:

  - platform: itunes
    host: !secret itunes_ip

ios:

  push:
    categories:
      - name: bike_to_work_day
        identifier: 'bikeday'
        actions:
          - identifier: 'BIKE_DAY'
            title: 'Bike Day'
            
nest:

  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  sensors:
    monitored_conditions:
      - 'co_status'
      - 'smoke_status'
      - 'battery_health'
      - 'color_status'

camera:

  - name: Right Last Person
    platform: generic
    still_image_url: !secret right_best_url

  - name: Left Last Person
    platform: generic
    still_image_url: !secret left_best_url

  - name: Front Last Person
    platform: generic
    still_image_url: !secret front_best_url

  - name: Back Last Person
    platform: generic
    still_image_url: !secret back_best_url

  - platform: synology
    url: !secret synology_int_url
    username: !secret syn_uname
    password: !secret hass_pass
    timeout: 120
#    verify_ssl: False


google:
             
  client_id: !secret google_email_client_id
  client_secret: !secret google_email_secret

zwave:
  usb_path: /dev/ttyACM0

weather:

  - platform: darksky
    api_key: !secret darksky_key
    name: Weather Forecast
    mode: daily
    scan_interval: 720
    
  - platform: openweathermap
    api_key: !secret openweathermap_key
    mode: hourly

#panel_iframe:
#cloud9:
#  title: cloud9
#  icon: mdi:wrench
#  url: http://hassbian.local:8181/ide.html
 

#mqtt:
#
#  broker: !secret pi_ip
#  client_id: homeassistant-001


mqtt:
  broker: !secret narnia_ip
  client_id: homeassistant-001
  username: !secret mqqt_uname
  password: !secret mqqt_pass

input_boolean:
  mix_playlist:
    name: Mix Playlist
    initial: off
  rock_playlist:
    name: Rock Playlist
    initial: off
  pop_playlist:
    name: Pop Playlist
    initial: off
  black_playlist:
    name: Black Playlist
    initial: off
  classical_playlist:
    name: Classical Playlist
    initial: off
  electronica_playlist:
    name: Electronica Playlist
    initial: off
  kids_playlist:
    name: Kids Playlist
    initial: off
    
input_select:
  sean_last_zone_dropdown:
    name: Sean Last Zone
    options:
      - home
      - ToAndel
      - Andel
      - Lazarska
      - ToCenter
      - Work
      - SmichovskeNad 
      - ToWineFood
      - WineFood
      - ToHornbachP5
      - HornbachP5
      - FromHornbachP5
      - BioStore
      - Yoga
      - Billa
      - Posta
      - IkeaZlicin
      - ToP6
      - FromP6HomeHighway
      - FromP6HomeBackWay
      - ToHornbachP6
      - FromHornbachP6
      - HornbachP6
    initial: home
    
  sean_location_dropdown:
    name: Sean Extended Location
    options:
      - Home
      - Left Home
      - Almost Home
      - Heading to Work
      - Heading to Center
      - Almost at Work
      - At Work
      - Waiting for Tram
      - Left Work
      - Heading Home
      - Heading to Andel
      - At Andel
      - Heading to Hornbach
      - At Hornbach
      - Heading to WineFood
      - At WineFood
      - At Billa
      - At Posta
      - Heading to P6
      - At Ikea
      - Driving
    initial: Home

  dishwasher_status:
    name: Dishwasher Status
    options:
      - Dirty
      - Starting Up
      - First Rinse
      - Washing
      - Final Rinse
      - Finishing Up
      - Drying
      - Clean
      - Emptying
    initial: Dirty
    icon: mdi:dishwasher

  living_room_last_mode:
    name: Last Heating Mode in Living Room
    options:
      - auto
      - manual

proximity:
  all_home: 
    devices:
      - device_tracker.seans_iphone_x
      - device_tracker.alenas_iphone
      - device_tracker.sophie
      - device_tracker.sophies_iphhshshshs
    tolerance: 50
    unit_of_measurement: km
  sean_home: 
    devices:
      - device_tracker.seans_iphone_x
    tolerance: 50
    unit_of_measurement: km
  alena_home: 
    devices:
      - device_tracker.alenas_iphone
    tolerance: 50
    unit_of_measurement: km
  sophie_home: 
    devices:
      - device_tracker.sophie
    tolerance: 50
    unit_of_measurement: km    
    
device_tracker:
  - platform: life360
    username: !secret life360_uname
    password: !secret life360_pw
    interval_seconds: 12
    filename: life360.conf
    show_as_state: places, driving, moving
    max_update_wait:
      minutes: 30

variable:
  dpd_variable:
    attributes:
      icon: mdi:delivery
      friendly_name: 'DPD'
      from: ''
      subject: ''
      body: ''
      date: ''
    restore: true

  posta_variable:
    attributes:
      icon: mdi:delivery
      friendly_name: 'Posta'
      from: ''
      subject: ''
      body: ''
      date: ''
    restore: true
      
  dhl_variable:
    attributes:
      icon: mdi:delivery
      friendly_name: 'DHL'
      from: ''
      subject: ''
      body: ''
      date: ''
    restore: true
    
  living_room_last_temp_variable:
    restore: true
    
cast:
  media_player:
    - host: !secret chromecast_ip
    
#smartthinq:
#  token: !secret smartthinq_token

notify:
  - name: sean_alena
    platform: group
    services:
      - service: ios_seans_iphone_x
      - service: ios_alenas_iphone
  - name: whole_family
    platform: group
    services:
      - service: ios_seans_iphone_x
      - service: ios_alenas_iphone  
      - service: ios_sophies_iphone_6

speedtestdotnet:
  monitored_conditions:
    - ping
    - download
    - upload

alarm_control_panel:
  - platform: mqtt
    name: "Home Alarm System"
    state_topic: "paradox/alarm/state/3"
    command_topic: "paradox/alarm/cmnd/3"
    qos: 1
    availability_topic: "paradox/ctrl/state"
    payload_available: "Connected"
    payload_not_available: "Disconnected"
    payload_disarm: “DISARM”
    payload_arm_home: “ARM_HOME”
    payload_arm_away: “ARM_AWAY”
#    code: !secret alarm_code
#    code_arm_required: false
#    code_disarm_required: true

alert:
  garage_door:
    name: Garage has been open for {{ relative_time(states.sensor.binary_sensor.garage_door_zone_14) }}
    done_message: Garage is closed
    entity_id: binary_sensor.garage_door_zone_14
    state: 'on'
    repeat: 
      - 10
      - 20
      - 30
      - 60
    can_acknowledge: true
    skip_first: true
    notifiers:
      - sean_alena

  front_door:
    name: Front door has been open for {{ relative_time(states.binary_sensor.front_door_zone_1) }}
    done_message: Front door is closed
    entity_id: binary_sensor.front_door_zone_1
    state: 'on'
    repeat: 
      - 10
      - 20
      - 30
      - 60
    can_acknowledge: true
    skip_first: true
    notifiers:
      - sean_alena

input_number:
  living_room_last_temp:
    name: Last Temp - Living Room
    min: 5
    max: 25
    step: 0.5