title: Home

#resources:
#
#  - url: /local/mini-media-player-bundle.js?v=1.0.1
#    type: module
#  - url: https://unpkg.com/moment@2.22.2/moment.js
#    type: js
#  - url: /local/custom_ui/calendar-card/calendar-card.js?v=1.0.1
#    type: module
#  - url: /local/button-card.js
#    type: module
#  - url: /local/air-visual-card.js 
#    type: js
#  - url: /local/custom-weather-card-chart.js
#    type: module
#  - url: /local/tracker-card.js?v=0.3.2
#    type: js
#  - url: /local/simple-thermostat.js?v=0.17.0
#    type: module
#  - url: /local/vertical-stack-in-card.js?v=v0.1.1
#    type: js
#  - url: /local/card-modder.js?v=f3d96f
#    type: js
#  - url: /local/card-tools.js?v=f5bb8e
#    type: js

resources:

  - url: /customcards/mini-media-player-bundle.js
    type: module
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: /customcards/custom_ui/calendar-card/calendar-card.js
    type: module
  - url: /customcards/button-card.js
    type: module
  - url: /customcards/air-visual-card.js 
    type: js
  - url: /customcards/custom-weather-card-chart.js
    type: module
  - url: /local/mini-graph-card-bundle.js?v=0.5.0
    type: module
  - url: /customcards/tracker-card.js
    type: js
  - url: /customcards/simple-thermostat.js
    type: module
  - url: /customcards/vertical-stack-in-card.js
    type: js
  - url: /customcards/card-modder.js
    type: js
  - url: /customcards/card-tools.js?track=true
    type: js
  - url: /customcards/github/thomasloven/layout-card.js?track=true
    type: js
  - url: /customcards/github/thomasloven/popup-card.js?track=true
    type: js
  - url: /customcards/github/thomasloven/browser-commander.js?track=true
    type: js
  - url: /customcards/github/thomasloven/slider-entity-row.js?track=true
    type: module
  - url: /local/secondaryinfo-entity-row.js
    type: module
  - url: /local/markdown-mod.js
    type: module
  - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=0.0.1
    type: module

#popup_cards:
#  sensor.dining_room_temperature:
#    title: Dining Room Climate History
#    card:
#      type: history-graph
#      entities:
#        - climate.dining_room
#        title: 'Entrance'
cch:
  exceptions:
    - conditions:
        user: kiosk
      config:
        hide_tabs: 0
        disable_sidebar: true
        default_tab: 1
        hide_help: true
        hide_config: true
        hide_unused: true
        voice: hide
        menu: hide
        notifications: hide  
        options: clock
        clock_format: 24
    - conditions:
        user: Alena
      config:
        hide_tabs: 1
        disable_sidebar: true
        default_tab: 0
        hide_help: true
        hide_config: true
        hide_unused: true
        voice: hide
        menu: hide
        notifications: hide  
    - conditions:
        user: Sophie
      config:
        hide_tabs: 1
        disable_sidebar: true
        default_tab: 0
        hide_help: true
        hide_config: true
        hide_unused: true
        voice: hide
        menu: hide
        notifications: hide  
    - conditions:
        user: Sean Straus
      config:
        hide_tabs: 1
        default_tab: 0
        hide_help: true
        hide_config: true
 

views:

  - !include /config/lovelace/Tab1_Home.yaml
  - !include /config/lovelace/Tab1a_Home_Kiosk.yaml
  - !include /config/lovelace/Tab2_Music.yaml
  - !include /config/lovelace/Tab3_Heat.yaml
  - !include /config/lovelace/Tab4_Cameras.yaml
  - !include /config/lovelace/Tab5_Alarm.yaml
  - !include /config/lovelace/Tab6_Weather.yaml
  - !include /config/lovelace/Tab7_Tech.yaml
     
#### EIGHTH TAB ####
#
#
#
#  - title: Utility Costs
#    panel: true
#    icon: mdi:power-plug
#    cards:
#    
#    - type: vertical-stack
#      cards:   
#
#      - type: iframe
#        url: https://pro.smappee.net/analyse
#        aspect_ratio: 100%
