title: Home

views:

  - !include /config/lovelace/Tab1_Home.yaml
  - !include /config/lovelace/Tab1a_Home_Kiosk.yaml
  - !include /config/lovelace/Tab2_Music.yaml
  - !include /config/lovelace/Tab3_Heat.yaml
  - !include /config/lovelace/Tab4_Cameras.yaml
  - !include /config/lovelace/Tab5_Appliances.yaml
  - !include /config/lovelace/Tab6_Alarm.yaml
  - !include /config/lovelace/Tab7_Weather.yaml
  - !include /config/lovelace/Tab8_Tech.yaml
    
    

custom_header:
  compact_mode: true
  background: var(--primary-background-color)
  exceptions:
    - conditions:
        user: kiosk
      config:
        hide_tabs: '0'
        disable_sidebar: true
        default_tab: '1'
        hide_help: true
        hide_config: true
        hide_unused: true
        voice_hide: true
#        menu_hide: true
        button_text:
          menu: 'menu'
          options: '{{ dayNameShort }}, {{ dayNum }} {{ monthNameShort }}       {{ hours24LZ }}:{{ minutesLZ }}'
#          options: '{{ dayNameShort }}. {{ monthNameShort }}. {{ dayNum }} {{ year4d }}'
    - conditions:
        user: Alena
      config:
        hide_tabs: '1'
        disable_sidebar: true
        default_tab: 0
        hide_help: true
        hide_config: true
        hide_unused: true
        voice_hide: true
        menu_hide: true
    - conditions:
        user: Sophie
      config:
        hide_tabs: '1'
        disable_sidebar: true
        default_tab: 0
        hide_help: true
        hide_config: true
        hide_unused: true
        voice_hide: true
        menu_hide: true
    - conditions:
        user: Sean Straus
      config:
        hide_tabs: '1'
        default_tab: 0
        hide_help: true
        hide_config: true
        voice_hide: true
#        header_text: '{{ hours12 }}:{{ minutesLZ }} {{ ampm }}'
#        button_text:
#          menu: '{{ dayNameShort }}. {{ monthNameShort }}. {{ dayNum }} {{ year4d }}'

#        header_text: '{{ hours12 }}:{{ minutesLZ }} {{ ampm }}'
#        button_text:
#          menu: '{{ dayNameShort }}. {{ monthNameShort }}. {{ dayNum }} {{ year4d }}'

#        options: clock
#        clock_format: 24
#        voice: hide
#        notifications: hide  
#        menu: hide
 
#### EIGHTH TAB ####
#
#
#
#  - title: Utility Costs
#    panel: true
#    icon: mdi:power-plug
#    cards:
#    
#    - type: vertical-stack
#      cards:   
#
#      - type: iframe
#        url: https://pro.smappee.net/analyse
#        aspect_ratio: 100%
