
- id: dishwasher_active_when_power
  alias: 'Set dishwasher active when power detected'
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: numeric_state
    entity_id: sensor.miele_dishwasher_power
    above: 20
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Dirty
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Emptying
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Starting Up

- id: dishwasher_first_rinse
  alias: 'Set dishwasher first rinse'
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: numeric_state
    entity_id: sensor.miele_dishwasher_power
    above: 1000
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Starting Up
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Clean
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Drying
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Emptying
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: First Rinse

- id: set_dishwasher_wash
  alias: 'Set dishwasher wash'
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: numeric_state
    entity_id: sensor.miele_dishwasher_power
    below: 100
    for:
      minutes: 10
  condition:
    condition: state
    entity_id: input_select.dishwasher_status
    state: First Rinse
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.dishwasher_status
      option: Washing

- id: set_dishwasher_rinse
  alias: Set dishwasher second rinse
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: numeric_state
    entity_id: sensor.miele_dishwasher_power
    above: 100
  condition:
    condition: state
    entity_id: input_select.dishwasher_status
    state: Washing
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Final Rinse
        
- id: set_dishwasher_finishing_up
  alias: 'Set dishwasher finishing up'
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: numeric_state
    entity_id: sensor.miele_dishwasher_power
    below: 25
    for:
      minutes: 10    
  condition:
    condition: state
    entity_id: input_select.dishwasher_status
    state: Final Rinse
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.dishwasher_status
      option: Finishing Up

- id: set_dishwasher_clean
  alias: 'Set dishwasher clean'
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: numeric_state
    entity_id: sensor.miele_dishwasher_power
    below: 1
    for:
      minutes: 2
  condition:
    condition: state
    entity_id: input_select.dishwasher_status
    state: Finishing Up
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.dishwasher_status
      option: Clean
 
# Once the dishwasher status has been 'Drying' for 30 minutes, mark the
# dishwasher as clean

- id: set_dishwasher_emptying
  alias: 'Set dishwasher emptying'
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: numeric_state
    entity_id: sensor.miele_dishwasher_power
    below: 0.01
    for:
      minutes: 5
  condition: 
    condition: state
    entity_id: input_select.dishwasher_status
    state: Clean
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.dishwasher_status
      option: Emptying

# When the power drops and the dishwasher is Clean or Drying, someone has
# turned the Dishwasher off and emptied it. We should do this when the state
# of the Dishwasher is clean or Finishing, just incase someone opens the
# Dishwasher before the 30 minute timeout has been reached.
 
- id: dishwasher_dirty_on_power_off
  alias: Set Dishwasher dirty when power off
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: numeric_state
    entity_id: sensor.miele_dishwasher_power
    below: 0.01
    for:
      minutes: 15
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Clean
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Drying
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Emptying
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.dishwasher_status
      option: Dirty

- id: notify_clean_dishes
  alias: Clean Dishes Notification
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: input_select.dishwasher_status
    to: 'Clean'
  action:
    service: notify.ios_alenas_iphone
    data:
      title: "Dishwasher Update"
      message: "Dishes Are Clean"



################### MIELE WASHING MACHINE ####################

#      - Empty
#      - Wash Cycle
#      - First Rest
#      - First Spin Cycle
#      - Second Rest
#      - Second Spin Cycle
#      - Clean

- id: set_miele_washing_wash_cycle
  alias: 'Set Miele washing machine wash cycle'
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: numeric_state
    entity_id: sensor.miele_washing_machine_power
    above: 2000
  condition:
    condition: state
    entity_id: input_select.miele_washing_machine_status
    state: Empty
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.miele_washing_machine_status
        option: Wash Cycle

- id: miele_washing_first_rest
  alias: 'Set Miele washing machine first rest'
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: numeric_state
    entity_id: sensor.miele_washing_machine_power
    below: 1000
    for: 
      minutes: 10
  condition:
    condition: state
    entity_id: input_select.miele_washing_machine_status
    state: Wash Cycle
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.miele_washing_machine_status
        option: First Rest

- id: set_miele_washing_first_spin_cycle
  alias: 'Set Miele washing machine first spin cycle'
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: numeric_state
    entity_id: sensor.miele_washing_machine_power
    above: 2000
  condition:
    condition: state
    entity_id: input_select.miele_washing_machine_status
    state: First Rest
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.miele_washing_machine_status
        option: First Spin Cycle
        
- id: set_miele_washing_second_rest
  alias: 'Set Miele washing machine second rest'
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: numeric_state
    entity_id: sensor.miele_washing_machine_power
    below: 1000
    for: 
      minutes: 12
  condition:
    condition: state
    entity_id: input_select.miele_washing_machine_status
    state: First Spin Cycle
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.miele_washing_machine_status
        option: Second Rest

- id: set_miele_washing_second_spin_cycle
  alias: 'Set Miele washing machine second spin cycle'
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: numeric_state
    entity_id: sensor.miele_washing_machine_power
    above: 2000
  condition:
    condition: state
    entity_id: input_select.miele_washing_machine_status
    state: Second Rest
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.miele_washing_machine_status
        option: Second Spin Cycle

- id: set_miele_washing_finishing
  alias: 'Set Miele washing machine finishing'
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: numeric_state
    entity_id: sensor.miele_washing_machine_power
    above: 525
    below: 700
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.miele_washing_machine_status
        state: Wash Cycle
      - condition: state
        entity_id: input_select.miele_washing_machine_status
        state: First Rest
      - condition: state
        entity_id: input_select.miele_washing_machine_status
        state: First Spin Cycle
      - condition: state
        entity_id: input_select.miele_washing_machine_status
        state: Second Rest
      - condition: state
        entity_id: input_select.miele_washing_machine_status
        state: Second Spin Cycle
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.miele_washing_machine_status
        option: Finishing

- id: miele_washing_clean
  alias: 'Set Miele washing machine clean'
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: numeric_state
    entity_id: sensor.miele_washing_machine_power
    below: 3
  condition:
    condition: state
    entity_id: input_select.miele_washing_machine_status
    state: Finishing
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.miele_washing_machine_status
        option: Clean

- id: miele_washing_empty
  alias: 'Set Miele washing machine empty'
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: numeric_state
    entity_id: sensor.miele_washing_machine_power
    below: 1
    for: 
      minutes: 2
  condition:
    condition: state
    entity_id: input_select.miele_washing_machine_status
    state: Clean
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.miele_washing_machine_status
        option: Empty

- id: notify_miele_clean
  alias: Miele clean laundry
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: input_select.miele_washing_machine_status
    to: 'Clean'
  action:
    service: notify.ios_alenas_iphone
    data:
      title: "Miele Washing Machine Update"
      message: "Laundry is Done"


################### LG WASHING MACHINE ####################

#      - Empty
#      - Starting Up
#      - Wash Cycle
#      - Spin Cycle
#      - Clean

- id: set_lg_washing_starting_up
  alias: 'Set lg washing machine starting up'
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: numeric_state
    entity_id: sensor.lg_washing_machine_power
    above: 75
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.lg_washing_machine_status
        state: Empty
      - condition: state
        entity_id: input_select.lg_washing_machine_status
        state: Clean
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.lg_washing_machine_status
        option: Starting Up

- id: lg_washing_wash_cycle
  alias: 'Set lg washing machine washing'
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: numeric_state
    entity_id: sensor.lg_washing_machine_power
    above: 1000
  condition:
    condition: state
    entity_id: input_select.lg_washing_machine_status
    state: Starting Up
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.lg_washing_machine_status
        option: Wash Cycle

- id: lg_washing_washing
  alias: 'Set lg washing machine spin cycle'
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: numeric_state
    entity_id: sensor.lg_washing_machine_power
    below: 1000
  condition:
    condition: state
    entity_id: input_select.lg_washing_machine_status
    state: Wash Cycle
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.lg_washing_machine_status
        option: Spin Cycle

- id: set_lg_washing_clean
  alias: 'Set lg washing machine clean'
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: numeric_state
    entity_id: sensor.lg_washing_machine_power
    below: 1
    for: 
      minutes: 3
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.lg_washing_machine_status
        state: Wash Cycle
      - condition: state
        entity_id: input_select.lg_washing_machine_status
        state: Spin Cycle
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.lg_washing_machine_status
        option: Clean

- id: lg_washing_empty
  alias: 'Set lg washing machine empty'
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: numeric_state
    entity_id: sensor.lg_washing_machine_power
    below: 0.01
    for: 
      minutes: 5
  condition:
    condition: state
    entity_id: input_select.lg_washing_machine_status
    state: Clean
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.lg_washing_machine_status
        option: Empty

- id: notify_lg_clean
  alias: LG clean laundry
  hide_entity: true
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: input_select.lg_washing_machine_status
    to: 'Clean'
  action:
    service: notify.ios_alenas_iphone
    data:
      title: "LG Washing Machine Update"
      message: "Laundry is Done"