##################################################
# AUTOMATIONS TO TURN DOWN HEAT FOR OPEN WINDOWS #
##################################################


- id: heat_down_open_living_room_auto
  alias: heat_down_open_living_room_auto
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.back_door
    to: 'on'
    for: 
      minutes: 3
  action:
    service: evohome.set_zone_override
    data:
      entity_id: climate.living_room
      setpoint: 12
      duration: {"minutes":240}
  condition:
    condition: state
    entity_id: input_select.active_heating_profile_living_room
    state: 'LIVING_ROOM_AUTO'
        


- id: heat_up_closed_living_room_auto
  alias: heat_up_closed_living_room_auto
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.back_door
    to: 'off'
  action:   
    - service: evohome.clear_zone_override
      data:
        entity_id: climate.living_room
  condition:
    condition: state
    entity_id: input_select.active_heating_profile_living_room
    state: 'LIVING_ROOM_AUTO'


- id: heat_down_open_sophies_room_auto
  alias: heat_down_open_sophies_room_auto
  trigger:
    platform: state
    entity_id: binary_sensor.sophies_room_ceiling_window
    to: 'on'
    for: 
      minutes: 3
  action:
    service: evohome.set_zone_override
    data:
      entity_id: climate.sophie_s_room
      setpoint: 12
      duration: {"minutes":240}
  condition:
    condition: state
    entity_id: input_select.active_heating_profile
    state: 'PROFILE_AUTO'
#  condition:
#    condition: template 
#    value_template: > 
#      {{ state_attr('climate.living_room', 'status').setpoint_status.setpoint_mode in 'FollowSchedule' }}


- id: heat_up_closed_sophies_room_auto
  alias: heat_up_closed_sophies_room_auto
  trigger:
    platform: state
    entity_id: binary_sensor.sophies_room_ceiling_window
    to: 'off'
  action:   
    - service: evohome.clear_zone_override
      data:
        entity_id: climate.sophie_s_room
  condition:
    condition: state
    entity_id: input_select.active_heating_profile
    state: 'PROFILE_AUTO'

- id: heat_down_open_sebastians_room_auto
  alias: heat_down_open_sebastians_room_auto
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.sebastians_room_left_window
    to: 'on'
    for: 
      minutes: 3
  action:
    service: evohome.set_zone_override
    data:
      entity_id: climate.sebastian_s_room
      setpoint: 12
      duration: {"minutes":240}
  condition:
    condition: state
    entity_id: input_select.active_heating_profile
    state: 'PROFILE_AUTO'

- id: heat_up_closed_sebastians_room_auto
  alias: heat_up_closed_sebastians_room_auto
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.sebastians_room_left_window
    to: 'off'
  action:   
    - service: evohome.clear_zone_override
      data:
        entity_id: climate.sebastian_s_room
  condition:
    condition: state
    entity_id: input_select.active_heating_profile
    state: 'PROFILE_AUTO'


- id: heat_down_open_master_closet_auto
  alias: heat_down_open_master_closet_auto
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_closet_left_window
    to: 'on'
    for: 
      minutes: 2
  action:
    service: evohome.set_zone_override
    data:
      entity_id: climate.master_closet
      setpoint: 12
      duration: {"minutes":240}
  condition:
    condition: state
    entity_id: input_select.active_heating_profile
    state: 'PROFILE_AUTO'
#  condition:
#    condition: template 
#    value_template: > 
#      {{ state_attr('climate.living_room', 'status').setpoint_status.setpoint_mode in 'FollowSchedule' }}


- id: heat_up_closed_master_closet_auto
  alias: heat_up_closed_master_closet_auto
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_closet_left_window
    to: 'off'
  action:   
    - service: evohome.clear_zone_override
      data:
        entity_id: climate.master_closet
  condition:
    condition: state
    entity_id: input_select.active_heating_profile
    state: 'PROFILE_AUTO'


- id: heat_down_open_laundry_auto
  alias: heat_down_open_laundry_auto
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.laundry_room_window_zone_13
    to: 'on'
  action:
    service: evohome.set_zone_override
    data:
      entity_id: climate.laundry_room
      setpoint: 12
      duration: {"minutes":240}
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.active_heating_profile
        state: 'PROFILE_AUTO'
      - condition: state
        entity_id: input_select.active_heating_profile
        state: 'PROFILE_A'
#  condition:
#    condition: template 
#    value_template: > 
#      {{ state_attr('climate.living_room', 'status').setpoint_status.setpoint_mode in 'FollowSchedule' }}


- id: heat_up_closed_laundry_auto
  alias: heat_up_closed_laundry_auto
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.laundry_room_window_zone_13
    to: 'off'
  action:   
    - service: evohome.clear_zone_override
      data:
        entity_id: climate.laundry_room
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.active_heating_profile
        state: 'PROFILE_AUTO'
      - condition: state
        entity_id: input_select.active_heating_profile
        state: 'PROFILE_A'


- id: heat_down_open_garage_auto
  alias: heat_down_open_garage_auto
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_garage_door
    to: 'on'
  action:
    service: evohome.set_zone_override
    data:
      entity_id: climate.garage
      setpoint: 5
      duration: {"minutes":240}
  condition:
    condition: state
    entity_id: input_select.active_heating_profile
    state: 'PROFILE_AUTO'
#  condition:
#    condition: template 
#    value_template: > 
#      {{ state_attr('climate.living_room', 'status').setpoint_status.setpoint_mode in 'FollowSchedule' }}


- id: heat_up_closed_garage_auto
  alias: heat_up_closed_garage_auto
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_garage_door
    to: 'off'
  action:   
    - service: evohome.clear_zone_override
      data:
        entity_id: climate.garage
  condition:
    condition: state
    entity_id: input_select.active_heating_profile
    state: 'PROFILE_AUTO'



######################################################
# AUTOMATIONS TO ADJUST HEAT BASED ON WEATHER REPORT #
######################################################
# this shit all got replaced by a badass python script
# that runs once a day at 12:30 AM

- id: set_heat_overrides_for_warm_weather
  alias: set_heat_overrides_for_warm_weather
  initial_state: 'true'
  trigger:
    platform: time
    at: '00:30:00'
  action:
    - service: python_script.set_heat_weather_override



####################################################
# Special Heating Cases Based on Location or Input #
####################################################

- id: sophie_room_heat_up_if_home
  alias: "Turn up the heat in sophie's room if she's home"
  initial_state: 'true'
  trigger:
    platform: time
    at: '7:50:00'
  condition:    
    condition: and
    conditions:
      - condition: state
        entity_id: 'device_tracker.sophie'
        state: 'home'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri    
  action:
    - service: evohome.set_zone_override
      data:
        entity_id: climate.sophie_s_room
        setpoint: 23
        duration: {"minutes":500}

- id: fire_in_fireplace_tomorrow
  alias: "Fire in Fireplace Tomorrow"
  trigger:
    platform: time
    at: '6:00:00'
  condition:    
    condition: state
    entity_id: input_boolean.fire_in_fireplace_tomorrow
    state: 'on'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.fire_in_fireplace_tomorrow
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.fire_in_fireplace_now

- id: fire_in_fireplace_now
  alias: "Fire in Fireplace Now"
  trigger:
    platform: state
    entity_id: input_boolean.fire_in_fireplace_now
    to: 'on'
  action:
    - service: evohome.set_zone_override
      data:
        entity_id: climate.dining_room
        setpoint: 21
        duration: {"minutes":840}
    - service: evohome.set_zone_override
      data:
        entity_id: climate.entrance
        setpoint: 21
        duration: {"minutes":840}
    - service: evohome.set_zone_override
      data:
        entity_id: climate.living_room
        setpoint: 21
        duration: {"minutes":840}

- id: fire_in_fireplace_now_turned_off
  alias: "Fire in Fireplace Now Off"
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: input_boolean.fire_in_fireplace_now
    to: 'off'
  action:
    - service: evohome.clear_zone_override
      data:
        entity_id: climate.dining_room
    - service: evohome.clear_zone_override
      data:
        entity_id: climate.entrance
    - service: evohome.clear_zone_override
      data:
        entity_id: climate.living_room

- id: working_from_home_now
  alias: "Working From Home Now"
  trigger:
    platform: state
    entity_id: input_boolean.working_from_home
    to: 'on'
  action:
    service: evohome.set_zone_override
    data:
      entity_id: climate.office_library
      setpoint: 23
      duration: {"minutes":480}

- id: working_from_home_today
  alias: "Working From Home Today"
  trigger:
    platform: time
    at: '10:00:00'
  condition:    
    - condition: state
      entity_id: input_boolean.working_from_home
      state: 'on'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri    
  action:
    service: evohome.set_zone_override
    data:
      entity_id: climate.office_library
      setpoint: 23
      duration: {"minutes":700}

#####################################
# Non heating related climate cases #
#####################################

- id: notify_windy_weather
  alias: 'Notify About Windy Weather'
  initial_state: 'true'
  trigger:
    minutes: '/60'
    platform: time_pattern
  condition:
    condition: template 
    value_template: >
      {{ if (states('sensor.dark_sky_wind_gust_1h')|float > 20) or (states('sensor.dark_sky_wind_gust_2h')|float > 20) or (states('sensor.dark_sky_wind_gust_3h')|float > 20) or (states('sensor.dark_sky_wind_gust_4h')|float > 20) or (states('sensor.dark_sky_wind_gust_5h')|float > 20) or (states('sensor.dark_sky_wind_gust_6h')|float > 20) or (states('sensor.dark_sky_wind_gust_7h')|float > 20) or (states('sensor.dark_sky_wind_gust_8h')|float > 20) or (states('sensor.dark_sky_wind_gust_9h')|float > 20) }}
  action:
    service: notify.mobile_app_sean_s_iphone_x
    data:
      title: "High Winds Warning"
    data_template:
      message: >
        {% if states('sensor.dark_sky_wind_gust_1h')|float > 20 %}
        High winds expected in the next hour. Please secure items outside.
        {% elif states('sensor.dark_sky_wind_gust_2h')|float > 20 %}
        High winds expected in 2 hours. Please secure items outside.
        {% elif states('sensor.dark_sky_wind_gust_3h')|float > 20 %}
        High winds expected in 3 hours. Please secure items outside.
        {% elif states('sensor.dark_sky_wind_gust_4h')|float > 20 %}
        High winds expected in 4 hours. Please secure items outside.
        {% elif states('sensor.dark_sky_wind_gust_5h')|float > 20 %}
        High winds expected in 5 hours. Please secure items outside.
        {% elif states('sensor.dark_sky_wind_gust_6h')|float > 20 %}
        High winds expected in 6 hours. Please secure items outside.
        {% elif states('sensor.dark_sky_wind_gust_7h')|float > 20 %}
        High winds expected in 7 hours. Please secure items outside.
        {% elif states('sensor.dark_sky_wind_gust_8h')|float > 20 %}
        High winds expected in 8 hours. Please secure items outside.
        {% elif states('sensor.dark_sky_wind_gust_9h')|float > 20 %}
        High winds expected in 9 hours. Please secure items outside.
        {% else %}
        Error
        {% endif %}
